version: '3.8'

services:
  flight-prediction:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/airlines"]
      interval: 30s
      timeout: 10s
      retries: 3
